name: verby_mobile_design_tokens
description: Verby Mobile Design Tokens

publish_to: 'none' 

version: 1.0.0

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.0

flutter:
  fonts:
  - family: Pretendard
    fonts:
      - asset: assets/fonts/Pretendard-ExtraBold.otf
        weight: 800
      - asset: assets/fonts/Pretendard-Bold.otf
        weight: 700
      - asset: assets/fonts/Pretendard-SemiBold.otf
        weight: 600
      - asset: assets/fonts/Pretendard-Medium.otf
        weight: 500
      - asset: assets/fonts/Pretendard-Regular.otf
        weight: 400